[package]
name = "encryptor"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Password-based encryption for Web3 wallet seed phrases"
readme = "README.md"
repository = "https://github.com/sumit03guha/encryptor"
keywords = ["wallet", "seed", "aes-gcm", "argon2id", "encryption"]
categories = ["cryptography"]
# publish     = true                       

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base64 = "0.22.1"
thiserror = "2.0.12"
zeroize = "1.7"

[package.metadata.readme]
template = "auto"
badges = ["docs.rs", "crates.io"]

[package.metadata.docs.rs]
all-features = true
